// Auto-generated. Do not edit!

// (in-package loop_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class KeyFrameHandleResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.keyframe_num = null;
    }
    else {
      if (initObj.hasOwnProperty('keyframe_num')) {
        this.keyframe_num = initObj.keyframe_num
      }
      else {
        this.keyframe_num = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type KeyFrameHandleResult
    // Serialize message field [keyframe_num]
    bufferOffset = _serializer.uint32(obj.keyframe_num, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type KeyFrameHandleResult
    let len;
    let data = new KeyFrameHandleResult(null);
    // Deserialize message field [keyframe_num]
    data.keyframe_num = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'loop_action/KeyFrameHandleResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '89b35da2e44418098ba2504142cdc556';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    uint32 keyframe_num
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new KeyFrameHandleResult(null);
    if (msg.keyframe_num !== undefined) {
      resolved.keyframe_num = msg.keyframe_num;
    }
    else {
      resolved.keyframe_num = 0
    }

    return resolved;
    }
};

module.exports = KeyFrameHandleResult;
