// Auto-generated. Do not edit!

// (in-package loop_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class KeyFrameHandleFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.saving = null;
    }
    else {
      if (initObj.hasOwnProperty('saving')) {
        this.saving = initObj.saving
      }
      else {
        this.saving = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type KeyFrameHandleFeedback
    // Serialize message field [saving]
    bufferOffset = _serializer.uint32(obj.saving, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type KeyFrameHandleFeedback
    let len;
    let data = new KeyFrameHandleFeedback(null);
    // Deserialize message field [saving]
    data.saving = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'loop_action/KeyFrameHandleFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '462113d864566488f4e0ca18af3ef254';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message 
    uint32 saving
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new KeyFrameHandleFeedback(null);
    if (msg.saving !== undefined) {
      resolved.saving = msg.saving;
    }
    else {
      resolved.saving = 0
    }

    return resolved;
    }
};

module.exports = KeyFrameHandleFeedback;
