// Generated by gencpp from file system_ctrl/algo_ctrl.msg
// DO NOT EDIT!


#ifndef SYSTEM_CTRL_MESSAGE_ALGO_CTRL_H
#define SYSTEM_CTRL_MESSAGE_ALGO_CTRL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace system_ctrl
{
template <class ContainerAllocator>
struct algo_ctrl_
{
  typedef algo_ctrl_<ContainerAllocator> Type;

  algo_ctrl_()
    : header()
    , algo_enable(false)
    , algo_reboot(false)
    , algo_reset(false)  {
    }
  algo_ctrl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , algo_enable(false)
    , algo_reboot(false)
    , algo_reset(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _algo_enable_type;
  _algo_enable_type algo_enable;

   typedef uint8_t _algo_reboot_type;
  _algo_reboot_type algo_reboot;

   typedef uint8_t _algo_reset_type;
  _algo_reset_type algo_reset;





  typedef boost::shared_ptr< ::system_ctrl::algo_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_ctrl::algo_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct algo_ctrl_

typedef ::system_ctrl::algo_ctrl_<std::allocator<void> > algo_ctrl;

typedef boost::shared_ptr< ::system_ctrl::algo_ctrl > algo_ctrlPtr;
typedef boost::shared_ptr< ::system_ctrl::algo_ctrl const> algo_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_ctrl::algo_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_ctrl::algo_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::system_ctrl::algo_ctrl_<ContainerAllocator1> & lhs, const ::system_ctrl::algo_ctrl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.algo_enable == rhs.algo_enable &&
    lhs.algo_reboot == rhs.algo_reboot &&
    lhs.algo_reset == rhs.algo_reset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::system_ctrl::algo_ctrl_<ContainerAllocator1> & lhs, const ::system_ctrl::algo_ctrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace system_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::system_ctrl::algo_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_ctrl::algo_ctrl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_ctrl::algo_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_ctrl::algo_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_ctrl::algo_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_ctrl::algo_ctrl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_ctrl::algo_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e37859a07726627da20d42fe4eb9bd2b";
  }

  static const char* value(const ::system_ctrl::algo_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe37859a07726627dULL;
  static const uint64_t static_value2 = 0xa20d42fe4eb9bd2bULL;
};

template<class ContainerAllocator>
struct DataType< ::system_ctrl::algo_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_ctrl/algo_ctrl";
  }

  static const char* value(const ::system_ctrl::algo_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_ctrl::algo_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool algo_enable\n"
"bool algo_reboot\n"
"bool algo_reset\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::system_ctrl::algo_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_ctrl::algo_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.algo_enable);
      stream.next(m.algo_reboot);
      stream.next(m.algo_reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct algo_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_ctrl::algo_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_ctrl::algo_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "algo_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.algo_enable);
    s << indent << "algo_reboot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.algo_reboot);
    s << indent << "algo_reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.algo_reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_CTRL_MESSAGE_ALGO_CTRL_H
