// Generated by gencpp from file system_ctrl/algo_status.msg
// DO NOT EDIT!


#ifndef SYSTEM_CTRL_MESSAGE_ALGO_STATUS_H
#define SYSTEM_CTRL_MESSAGE_ALGO_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace system_ctrl
{
template <class ContainerAllocator>
struct algo_status_
{
  typedef algo_status_<ContainerAllocator> Type;

  algo_status_()
    : header()
    , algo_status()  {
    }
  algo_status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , algo_status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _algo_status_type;
  _algo_status_type algo_status;





  typedef boost::shared_ptr< ::system_ctrl::algo_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_ctrl::algo_status_<ContainerAllocator> const> ConstPtr;

}; // struct algo_status_

typedef ::system_ctrl::algo_status_<std::allocator<void> > algo_status;

typedef boost::shared_ptr< ::system_ctrl::algo_status > algo_statusPtr;
typedef boost::shared_ptr< ::system_ctrl::algo_status const> algo_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_ctrl::algo_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_ctrl::algo_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::system_ctrl::algo_status_<ContainerAllocator1> & lhs, const ::system_ctrl::algo_status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.algo_status == rhs.algo_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::system_ctrl::algo_status_<ContainerAllocator1> & lhs, const ::system_ctrl::algo_status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace system_ctrl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::system_ctrl::algo_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_ctrl::algo_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_ctrl::algo_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_ctrl::algo_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_ctrl::algo_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_ctrl::algo_status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_ctrl::algo_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea3cca9ddd69cc9250ffcf7d901d6d13";
  }

  static const char* value(const ::system_ctrl::algo_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea3cca9ddd69cc92ULL;
  static const uint64_t static_value2 = 0x50ffcf7d901d6d13ULL;
};

template<class ContainerAllocator>
struct DataType< ::system_ctrl::algo_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_ctrl/algo_status";
  }

  static const char* value(const ::system_ctrl::algo_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_ctrl::algo_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string algo_status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::system_ctrl::algo_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_ctrl::algo_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.algo_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct algo_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_ctrl::algo_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_ctrl::algo_status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "algo_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.algo_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_CTRL_MESSAGE_ALGO_STATUS_H
