(cl:defpackage loop_action-msg
  (:use )
  (:export
   "<KEYFRAMEHANDLEACTION>"
   "KEYFRAMEHANDLEACTION"
   "<KEYFRAMEHANDLEACTIONFEEDBACK>"
   "KEYFRAMEHANDLEACTIONFEEDBACK"
   "<KEYFRAMEHANDLEACTIONGOAL>"
   "KEYFRAMEHANDLEACTIONGOAL"
   "<KEYFRAMEHANDLEACTIONRESULT>"
   "KEYFRAMEHANDLEACTIONRESULT"
   "<KEYFRAMEHANDLEFEEDBACK>"
   "KEYFRAMEHANDLEFEEDBACK"
   "<KEYFRAMEHANDLEGOAL>"
   "KEYFRAMEHANDLEGOAL"
   "<KEYFRAMEHANDLERESULT>"
   "KEYFRAMEHANDLERESULT"
  ))

