; Auto-generated. Do not edit!


(cl:in-package loop_action-msg)


;//! \htmlinclude KeyFrameHandleGoal.msg.html

(cl:defclass <KeyFrameHandleGoal> (roslisp-msg-protocol:ros-message)
  ((function
    :reader function
    :initarg :function
    :type cl:integer
    :initform 0))
)

(cl:defclass KeyFrameHandleGoal (<KeyFrameHandleGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <KeyFrameHandleGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'KeyFrameHandleGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name loop_action-msg:<KeyFrameHandleGoal> is deprecated: use loop_action-msg:KeyFrameHandleGoal instead.")))

(cl:ensure-generic-function 'function-val :lambda-list '(m))
(cl:defmethod function-val ((m <KeyFrameHandleGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader loop_action-msg:function-val is deprecated.  Use loop_action-msg:function instead.")
  (function m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <KeyFrameHandleGoal>) ostream)
  "Serializes a message object of type '<KeyFrameHandleGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'function)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'function)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'function)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'function)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <KeyFrameHandleGoal>) istream)
  "Deserializes a message object of type '<KeyFrameHandleGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'function)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'function)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'function)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'function)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<KeyFrameHandleGoal>)))
  "Returns string type for a message object of type '<KeyFrameHandleGoal>"
  "loop_action/KeyFrameHandleGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'KeyFrameHandleGoal)))
  "Returns string type for a message object of type 'KeyFrameHandleGoal"
  "loop_action/KeyFrameHandleGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<KeyFrameHandleGoal>)))
  "Returns md5sum for a message object of type '<KeyFrameHandleGoal>"
  "142cf54a24c318f027c4b4907179cc04")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'KeyFrameHandleGoal)))
  "Returns md5sum for a message object of type 'KeyFrameHandleGoal"
  "142cf54a24c318f027c4b4907179cc04")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<KeyFrameHandleGoal>)))
  "Returns full string definition for message of type '<KeyFrameHandleGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 function  # 1 for add keyframe, 2 for save map keyframe~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'KeyFrameHandleGoal)))
  "Returns full string definition for message of type 'KeyFrameHandleGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 function  # 1 for add keyframe, 2 for save map keyframe~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <KeyFrameHandleGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <KeyFrameHandleGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'KeyFrameHandleGoal
    (cl:cons ':function (function msg))
))
