; Auto-generated. Do not edit!


(cl:in-package loop_action-msg)


;//! \htmlinclude KeyFrameHandleFeedback.msg.html

(cl:defclass <KeyFrameHandleFeedback> (roslisp-msg-protocol:ros-message)
  ((saving
    :reader saving
    :initarg :saving
    :type cl:integer
    :initform 0))
)

(cl:defclass KeyFrameHandleFeedback (<KeyFrameHandleFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <KeyFrameHandleFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'KeyFrameHandleFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name loop_action-msg:<KeyFrameHandleFeedback> is deprecated: use loop_action-msg:KeyFrameHandleFeedback instead.")))

(cl:ensure-generic-function 'saving-val :lambda-list '(m))
(cl:defmethod saving-val ((m <KeyFrameHandleFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader loop_action-msg:saving-val is deprecated.  Use loop_action-msg:saving instead.")
  (saving m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <KeyFrameHandleFeedback>) ostream)
  "Serializes a message object of type '<KeyFrameHandleFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'saving)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'saving)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'saving)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'saving)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <KeyFrameHandleFeedback>) istream)
  "Deserializes a message object of type '<KeyFrameHandleFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'saving)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'saving)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'saving)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'saving)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<KeyFrameHandleFeedback>)))
  "Returns string type for a message object of type '<KeyFrameHandleFeedback>"
  "loop_action/KeyFrameHandleFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'KeyFrameHandleFeedback)))
  "Returns string type for a message object of type 'KeyFrameHandleFeedback"
  "loop_action/KeyFrameHandleFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<KeyFrameHandleFeedback>)))
  "Returns md5sum for a message object of type '<KeyFrameHandleFeedback>"
  "462113d864566488f4e0ca18af3ef254")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'KeyFrameHandleFeedback)))
  "Returns md5sum for a message object of type 'KeyFrameHandleFeedback"
  "462113d864566488f4e0ca18af3ef254")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<KeyFrameHandleFeedback>)))
  "Returns full string definition for message of type '<KeyFrameHandleFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message ~%uint32 saving~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'KeyFrameHandleFeedback)))
  "Returns full string definition for message of type 'KeyFrameHandleFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message ~%uint32 saving~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <KeyFrameHandleFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <KeyFrameHandleFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'KeyFrameHandleFeedback
    (cl:cons ':saving (saving msg))
))
