// Generated by gencpp from file sensor_pub/ImageInfo.msg
// DO NOT EDIT!


#ifndef SENSOR_PUB_MESSAGE_IMAGEINFO_H
#define SENSOR_PUB_MESSAGE_IMAGEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sensor_pub
{
template <class ContainerAllocator>
struct ImageInfo_
{
  typedef ImageInfo_<ContainerAllocator> Type;

  ImageInfo_()
    : header()
    , exposure(0)
    , analog_gain(0.0)
    , digital_gain(0.0)  {
    }
  ImageInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , exposure(0)
    , analog_gain(0.0)
    , digital_gain(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _exposure_type;
  _exposure_type exposure;

   typedef float _analog_gain_type;
  _analog_gain_type analog_gain;

   typedef float _digital_gain_type;
  _digital_gain_type digital_gain;





  typedef boost::shared_ptr< ::sensor_pub::ImageInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_pub::ImageInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ImageInfo_

typedef ::sensor_pub::ImageInfo_<std::allocator<void> > ImageInfo;

typedef boost::shared_ptr< ::sensor_pub::ImageInfo > ImageInfoPtr;
typedef boost::shared_ptr< ::sensor_pub::ImageInfo const> ImageInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_pub::ImageInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_pub::ImageInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_pub::ImageInfo_<ContainerAllocator1> & lhs, const ::sensor_pub::ImageInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.exposure == rhs.exposure &&
    lhs.analog_gain == rhs.analog_gain &&
    lhs.digital_gain == rhs.digital_gain;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_pub::ImageInfo_<ContainerAllocator1> & lhs, const ::sensor_pub::ImageInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_pub

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensor_pub::ImageInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_pub::ImageInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_pub::ImageInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_pub::ImageInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_pub::ImageInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_pub::ImageInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_pub::ImageInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26da7a856946892d3a235072866504a8";
  }

  static const char* value(const ::sensor_pub::ImageInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26da7a856946892dULL;
  static const uint64_t static_value2 = 0x3a235072866504a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_pub::ImageInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_pub/ImageInfo";
  }

  static const char* value(const ::sensor_pub::ImageInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_pub::ImageInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 exposure\n"
"float32 analog_gain\n"
"float32 digital_gain\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sensor_pub::ImageInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_pub::ImageInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.exposure);
      stream.next(m.analog_gain);
      stream.next(m.digital_gain);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_pub::ImageInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_pub::ImageInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "exposure: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.exposure);
    s << indent << "analog_gain: ";
    Printer<float>::stream(s, indent + "  ", v.analog_gain);
    s << indent << "digital_gain: ";
    Printer<float>::stream(s, indent + "  ", v.digital_gain);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_PUB_MESSAGE_IMAGEINFO_H
